name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
